version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install telebot pymongo aiohttp
            pip install pymongo python-telegram-bot pyTelegramBotAPI certifi
      - run:
          name: Give execution permission to LEGEND
          command: chmod +x LEGEND
      - run:
          name: Run the Python script
          command: python LEGEND.py
      - run:
          name: Run LEGEND binary file
          command: ./LEGEND
